use opencli_rs_core::Strategy;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Options for the explore command.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExploreOptions {
    /// Timeout in seconds (default 120).
    pub timeout: Option<u64>,
    /// Maximum number of auto-scrolls (default 5).
    pub max_scrolls: Option<u32>,
    /// Whether to capture network traffic (default true).
    pub capture_network: Option<bool>,
}

impl Default for ExploreOptions {
    fn default() -> Self {
        Self {
            timeout: Some(120),
            max_scrolls: Some(5),
            capture_network: Some(true),
        }
    }
}

/// The manifest produced by an explore run — summarizes the site's API surface.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExploreManifest {
    pub url: String,
    pub title: Option<String>,
    pub endpoints: Vec<DiscoveredEndpoint>,
    /// Detected frontend framework (React, Vue, Angular, etc.).
    pub framework: Option<String>,
    /// Detected state store (Pinia, Vuex, Redux, etc.).
    pub store: Option<String>,
    /// Auth-related indicators found in request headers/cookies.
    pub auth_indicators: Vec<String>,
}

/// A single discovered API endpoint with analysis metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiscoveredEndpoint {
    pub url: String,
    pub method: String,
    pub content_type: Option<String>,
    pub fields: Vec<FieldInfo>,
    /// Confidence score from 0.0 to 1.0.
    pub confidence: f64,
    pub auth_level: Strategy,
    pub sample_response: Option<Value>,
}

/// A field discovered within an API response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldInfo {
    pub name: String,
    /// Semantic role: title, url, author, score, date, etc.
    pub role: Option<String>,
    /// Type: string, number, boolean, array.
    pub field_type: String,
}

/// A candidate adapter generated by synthesize.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdapterCandidate {
    pub site: String,
    pub name: String,
    pub description: String,
    pub strategy: Strategy,
    /// Generated YAML content for the adapter.
    pub yaml: String,
    pub confidence: f64,
}

/// Options for the synthesize command.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SynthesizeOptions {
    pub site: Option<String>,
    pub goal: Option<String>,
}

/// Result of the cascade auth-strategy probe.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CascadeResult {
    pub url: String,
    pub strategy: Strategy,
    pub tested: Vec<StrategyTestResult>,
}

/// Outcome of testing a single strategy against an endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyTestResult {
    pub strategy: Strategy,
    pub success: bool,
    pub status_code: Option<u16>,
    pub has_data: bool,
}

// ── Constants ────────────────────────────────────────────────────────────────

/// URL parameters that should be ignored when normalizing endpoints (volatile/tracking).
pub(crate) const VOLATILE_PARAMS: &[&str] = &[
    "_", "t", "ts", "timestamp", "cb", "callback", "nonce", "rand", "random",
    "spm_id_from", "vd_source", "from_spmid", "seid", "rt", "mid",
    "web_location", "platform", "w_rid", "wts",
];

/// Parameters that indicate search capability.
pub(crate) const SEARCH_PARAMS: &[&str] = &[
    "q", "query", "keyword", "keywords", "search", "search_query", "w", "wd", "kw",
];

/// Parameters that indicate pagination.
pub(crate) const PAGINATION_PARAMS: &[&str] = &[
    "page", "pn", "p", "offset", "cursor", "next", "page_num", "pageNum",
];

/// Parameters that indicate limit/page-size.
pub(crate) const LIMIT_PARAMS: &[&str] = &[
    "limit", "ps", "size", "pageSize", "page_size", "count", "num", "per_page",
];

/// Well-known field roles and their common aliases.
pub(crate) const FIELD_ROLES: &[(&str, &[&str])] = &[
    ("title", &["title", "name", "text", "headline", "subject"]),
    ("url", &["url", "link", "href", "uri", "goto", "short_link"]),
    ("author", &["author", "owner", "user", "creator", "nickname", "uname"]),
    ("score", &["score", "likes", "like_count", "view", "views", "view_count", "hot", "stat"]),
    ("time", &["time", "date", "created", "created_at", "ctime", "pubdate", "publish_time"]),
];

/// Known site hostname aliases.
pub(crate) const KNOWN_SITE_ALIASES: &[(&str, &str)] = &[
    ("x.com", "twitter"),
    ("twitter.com", "twitter"),
    ("news.ycombinator.com", "hackernews"),
    ("www.zhihu.com", "zhihu"),
    ("www.bilibili.com", "bilibili"),
    ("search.bilibili.com", "bilibili"),
    ("www.v2ex.com", "v2ex"),
    ("www.reddit.com", "reddit"),
    ("www.xiaohongshu.com", "xiaohongshu"),
    ("www.douban.com", "douban"),
    ("www.weibo.com", "weibo"),
    ("www.bbc.com", "bbc"),
];
